source :gemcutter
gem 'sqlite3-ruby', '1.2.5'
gem 'cucumber', '0.8.5'
gem 'cucumber-rails', '0.3.2'
gem "gherkin", "2.1.4"
gem "rspec", "2.0.0.beta.20"
gem 'rspec-rails', "2.0.0.beta.20"
gem 'rails', '3.0.0'
gem 'ruby-debug', '>= 0.10.3'
gem 'spork', :path => File.expand_path("../../..", File.dirname(__FILE__))
