language: ruby

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec rspec --version

script: ./bin/ci/ci.sh

rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head

notifications:
  email: false
