source :gemcutter
gem 'sqlite3-ruby', '1.2.5'
gem 'cucumber', '0.7.3'
gem 'cucumber-rails'
gem 'gherkin', '1.0.27'
gem 'rspec',  '1.3.0'
gem 'rspec-rails', '>= 1.3.2'
gem 'rails', '2.3.8'
gem 'ruby-debug', '>= 0.10.3'
gem 'spork', :path => File.expand_path("../../..", File.dirname(__FILE__))